link:
  thingscloud:
    freeswitch:
      esl:
        inbound:
          defaultPassword: ClueCon
          performance: false
          performanceCostTime: 200
          servers:
            - host: 127.0.0.1
              port: 8021
              timeoutSeconds: 5
            - host: 127.0.0.1
              port: 8021
          events:
            - all
#logging:
#  level:
#    link: DEBUG
